[MIG] hr_transfer: migrate to 14.0
trevi-software/trevi-hr pull request #24
Opened 2022-02-08 10:01 UTC by al3ba

2022-02-22 16:59 UTC, mtelahun requested changes
Ah sorry. I didn't finish the review.

2022-02-22 16:59 UTC, mtelahun commented on hr_transfer/models/hr_transfer.py
> +class HrTransfer(models.Model):
Multi-company consistency:
_check_company_auto needs to be set
check_company=True needs to be set on relational fields whose models contain a company_id

https://www.odoo.com/documentation/15.0/developer/howtos/company.html

2022-02-22 16:59 UTC, mtelahun commented on hr_transfer/models/hr_transfer.py
> +    company_id = fields.Many2one(
Maybe this needs to stop being a related field, and instead should just have a default value. Not sure which is the right way to go.

2022-02-22 16:59 UTC, mtelahun commented on hr_transfer/models/hr_transfer.py
> +        for transfer in self.filtered("employee_id"):
I'm not sure filtered() does what you think it does in this case.

2022-02-22 16:59 UTC, mtelahun commented on hr_transfer/security/ir.model.access.csv
> +access_hr_transfer_default,access_hr_transfer_default,model_hr_department_transfer,,0,0,0,0
What use is this?

2022-02-22 16:59 UTC, mtelahun commented on hr_transfer/data/hr_transfer_cron.xml
> +    </record>
The xml data to declare scheduled actions has changed in v14.

2022-03-16 10:24 UTC, al3ba commented on hr_transfer/data/hr_transfer_cron.xml
> +    </record>
I have made the changes introduced in v11 (model -> model_id and function + args -> code) apart from that, I can't find any changes introduced in v14.

2022-03-16 10:24 UTC, al3ba commented on hr_transfer/security/ir.model.access.csv
> +access_hr_transfer_default,access_hr_transfer_default,model_hr_department_transfer,,0,0,0,0
sorry, it was a typo

2022-03-22 12:53 UTC, mtelahun commented on hr_transfer/security/ir.model.access.csv
> +access_hr_transfer_default,access_hr_transfer_default,model_hr_department_transfer,,1,0,0,0
should the group be empty? or should it be base.group_user

2022-03-22 12:56 UTC, mtelahun approved these changes
I only have one additional comment on the group access csv. Other than that looks good. If you can address my comment go ahead and merge.

2022-03-23 10:26 UTC, merged